class StateService {
  // static final List<String> states = [
  //   '12th Main Road',
  //   'AGS Complex Navalur',
  //   'Aavin Dairy Ambattur',
  //   'Abirami Theatre',
  //   'Adyar Depot',
  //   'Adyar Gandhi Nagar',
  //   'Adyar Signal',
  //   'Akkarai or Water Supply Head Work',
  //   'Akshaya Padur',
  //   'Alagappa Schools',
  //   'Alandur Court',
  //   'Albert Theatre',
  //   'All India Radio Light House',
  //   'Alwarthirunagar',
  //   'Ambattur I.T. Park',
  //   'Ambattur Industrial Estate',
  //   'Ambattur OT Bus Stand',
  //   'Amman Kovil',
  //   'Anakaputhur Amman Kovil',
  //   'Anakaputhur Higher Secondary School',
  //   'Anand Theatre',
  //   'Anandbagh',
  //   'Andakuppam',
  //   'Andhra Mahila Sabha Hospital Or Sathya Studio',
  //   'Anna Arch',
  //   'Anna Nagar Roundtana',
  //   'Anna Nagar West Depot',
  //   'Anna Square',
  //   'Anna University Or Engineer College',
  //   'Arakkambakkam',
  //   'Arakkambakkam Road Junction',
  //   'Arun Hotel',
  //   'Asan College',
  //   'Ashok Nagar Canara Bank',
  //   'Ashok Pillar',
  //   'Asian Games',
  //   'Avadi Check Post',
  //   'Avadi Government Hospital',
  //   'Avadi HVF Road',
  //   'Avadi Market',
  //   'Avadi Mosque',
  //   'Avadi Terminal',
  //   'Avichi School',
  //   'Ayanavaram Bus Depot',
  //   'Ayanavaram Signal',
  //   'BSNL Office',
  //   'Baby Nagar',
  //   'Bai Kadai Moulivakkam',
  //   'Balaji Nagar Medavakkam',
  //   'Bangarampettai',
  //   'Basin Bridge Railway Station',
  //   'Bethal Nagar',
  //   'Bhaktavatsalam Memorial College',
  //   'Bharathi Nagar',
  //   'Bharathiyar Nagar',
  //   'Bhuari Hotel',
  //   'Blue Star',
  //   'Britannia Bus Stop Padi',
  //   'Broadway',
  //   'Butt Road',
  //   'CIPET',
  //   'CIT Nagar',
  //   'CMBT Bus Depot',
  //   'CPWD Quarters',
  //   'Camp Road Junction Selaiyur',
  //   'Canara Bank',
  //   'Central Dental College',
  //   'Chekkady',
  //   'Chellammal College',
  //   'Chenganmal Road Junction',
  //   'Chettinad Hospital',
  //   'Chidambaram Store',
  //   'Chromepet',
  //   'Collector Nagar',
  //   'Commissioner Office',
  //   'Concorde',
  //   'D B Jain College',
  //   'DLF Or L and T',
  //   'DMS',
  //   'Das Prakash Hotel Or Petrol Pump',
  //   'Dasa Mahan',
  //   'Dhandeeswaran Nagar',
  //   'Dharma Prakash  or MCTM School',
  //   'Dollar Or Accenture',
  //   'Dr. BR Ambedkar Statue.',
  //   'Dunlop',
  //   'E S I Hospital',
  //   'East Tambaram Convent',
  //   'Egattur',
  //   'Egmore Railway Station',
  //   'Ekkattuthangal Or聽Ambal Nagar',
  //   'Ezhurammal Koil',
  //   'Foreshore Estate MTC Bus Stop',
  //   'Gandhi Road',
  //   'Ganesh Nagar',
  //   'Gemini P H',
  //   'Gemini P H Or U S I S',
  //   'Gerugambakkam',
  //   'Golden Flats',
  //   'Gopala Krishna Theatre',
  //   'Govardanagiri',
  //   'Government School Sholinganallur',
  //   'Guindy Bus Terminus',
  //   'Guindy Industrial Estate',
  //   'Guindy M K N Salai',
  //   'Guru Nanak College',
  //   'Halda',
  //   'Hindustan College',
  //   'Hotel Everest',
  //   'I G P',
  //   'I.C.F. Annexe',
  //   'ICF',
  //   'IIT Madras Or Guindy National Park',
  //   'IT Park Siruseri Or Muttukadu',
  //   'Ice Factory',
  //   'Ice House Police Station',
  //   'Infoview Thoraipakkam',
  //   'Injambakkam',
  //   'Iyankulam',
  //   'Iyappanthangal',
  //   'Iyyappanthangal Bus Depot',
  //   'JB Estate',
  //   'Jai Garden',
  //   'Jaya Jaya Sankara International School',
  //   'Jayanthi Theatre',
  //   'Joint Office',
  //   'K.K Nagar Telephone Exchange Jaffarkhanpet',
  //   'Kaduvetti',
  //   'Kaiveli',
  //   'Kalaimagal Nagar',
  //   'Kalavakkam',
  //   'Kalavakkam School',
  //   'Kallarai',
  //   'Kallukkadai',
  //   'Kamarajapuram Camp Road',
  //   'Kambar Arangam',
  //   'Kanathur',
  //   'Kandanchavadi',
  //   'Kandhaswami Temple Tank Thiruporur',
  //   'Kannadapalayam Junction',
  //   'Kannagi Statue Or Presidency College',
  //   'Kannaigapuram',
  //   'Kannigapuram',
  //   'Karambakkam',
  //   'Karapakkam',
  //   'Karayanchavadi',
  //   'Karima Nagar',
  //   'Karima Nagar Company',
  //   'Kasi Theatre',
  //   'Katathotti',
  //   'Kathipara',
  //   'Kattupakkam',
  //   'Kazhipattur',
  //   'Keelmanabedu',
  //   'Kelambakkam Bus Terminal',
  //   'Kelambakkmm Police Station',
  //   'Kendriya Vidyalaya Minambakkam',
  //   'Kesavardhini',
  //   'Kilkattalai',
  //   'Kodambakkam Power House',
  //   'Koman Nagar Road Junction',
  //   'Korattur Bus Terminus',
  //   'Korrattur Signal Or East Avenue',
  //   'Kottivakkam',
  //   'Kovalam',
  //   'Kovalam Chamjarai',
  //   'Kovalam Kelambakam Road Junction',
  //   'Kovarthanagiri',
  //   'Kovilpadagai',
  //   'Kovilpadagai Road Junction',
  //   'Kovilpathagai Bharathi Nagar',
  //   'Kovur E B Office',
  //   'Koyambedu Chathiram',
  //   'Krishna Nagar',
  //   'Kumaran Nagar',
  //   'Kundrathur Bus Depot',
  //   'Kundrathur Nalu Road Or Kolachery Junction',
  //   'Kundrathur Or Thandalam',
  //   'Kundumedu',
  //   'Kunnukadu Alamaram',
  //   'Lakshmi Nagar',
  //   'Liberty',
  //   'Lic',
  //   'Little Mount',
  //   'Loyala College',
  //   'M.G.R Salai Nungambakkam Or Plam Grove',
  //   'MGR Central Station',
  //   'MGR Medical University',
  //   'MMDA Colony Road Junction',
  //   'MRC Nagar',
  //   'Madha Hospital And College',
  //   'Madhanandapuram',
  //   'Madhya Kailash',
  //   'Madipakkam Road Junction',
  //   'Madras University',
  //   'Maduvankarai',
  //   'Mageshwari Nagar',
  //   'Mahalakshmi Nagar',
  //   'Manacherry',
  //   'Manikandapuram',
  //   'Mannurpet',
  //   'Marina Beach',
  //   'Medavakkam Colony Or Puliamaram',
  //   'Medavakkam Junction',
  //   'Medavakkam Kellys',
  //   'Medavakkam Mental Hospital',
  //   'Meera Nagar',
  //   'Meersahibpet Market',
  //   'Mel Menambedu',
  //   'Melpakkam',
  //   'Metrological Department Sterling Road',
  //   'Mettukuppam',
  //   'Military Quarters',
  //   'Miot Hospital',
  //   'Mogaipair Road Junction',
  //   'Moolakothalam',
  //   'Moon Light',
  //   'Moondram Kattalai',
  //   'Moorai Anna Nagar',
  //   'Moorthy Nagar',
  //   'Moovarasampettai',
  //   'Motcham Theatre Or GRT',
  //   'Moulivakkam L And T',
  //   'Msic College Annamalai Puram',
  //   'Mugalivakkam',
  //   'Munipillai Chathiram',
  //   'Murugan Kalyana Mandapam',
  //   'Murugappa Polytechnic',
  //   'Muttukadu',
  //   'Muttukadu Boat House',
  //   'NIEPMD',
  //   'Nainar Kuppam or  Uthandi Colony',
  //   'Nandanam YMCA',
  //   'Nanganallur MGR Road',
  //   'Nanganallur Market',
  //   'Narayanapuram',
  //   'Nathamuni Talkies',
  //   'Navallur',
  //   'Nazarathpet',
  //   'Nazarathpet Police Check Post',
  //   'Nellankarai',
  //   'New College',
  //   'Noor Hotel',
  //   'Nungambakkam Railway Station',
  //   'Nurse Quarters',
  //   'Oil Mill',
  //   'Okkiyampet',
  //   'Otteri',
  //   'P U Office Sholinganallur',
  //   'PTC Quarters',
  //   'Padi Lucas TVS',
  //   'Padur',
  //   'Palavakkam',
  //   'Pallavan Salai',
  //   'Pallavaram',
  //   'Pallikaranai',
  //   'Pallikaranai Government School',
  //   'Pallikaranai Kamachi Hospital',
  //   'Pammal',
  //   'Panaiyur',
  //   'Panchayat Board',
  //   'Panjabur or Yellow board',
  //   'Parrys Corner',
  //   'Paruthipattu Road Junction',
  //   'Pattalam',
  //   'Pattravakkam',
  //   'Pattullos Road Or聽Express Avenue',
  //   'Pazhavanthangal Subway',
  //   'Periyapanicherr',
  //   'Periyapanicherry Church',
  //   'Periyar Salai',
  //   'Perungudi',
  //   'Pillaiyar Koil',
  //   'Pillayar Kovil Or Manancheri',
  //   'Podi Kadai',
  //   'Ponniamman Kovil',
  //   'Poonamallee',
  //   'Poonamallee Government Hospital',
  //   'Poonamallee Municipality Or聽Kumananchavadi',
  //   'Poonamallee Terminus',
  //   'Poondi Bazaar',
  //   'Porur',
  //   'Porur Arcot Road',
  //   'Porur E B Office',
  //   'Porur Shakthi Nagar',
  //   'Post Office',
  //   'Prnaipalai Or Alandur',
  //   'Pudupet',
  //   'Pulianthope Police station P1',
  //   'Puliyanthopu Tb Hospital',
  //   'Purasaivakkam Tank',
  //   'Queen Marys College',
  //   'Raaki Theatre',
  //   'Race Course Road',
  //   'Railway Quarters',
  //   'Raj Bhavan Quarters',
  //   'Ramachandra Hospital',
  //   'Rasi Silk',
  //   'Roja Medical',
  //   'Royapettah Hospital',
  //   'S I E T College',
  //   'S R P Tools',
  //   'SA Engineering college',
  //   'SBI Bank Pattravakkam',
  //   'SHB',
  //   'SIDCO Nagar',
  //   'SRP Tools',
  //   'SSN College',
  //   'Sai Baba Temple',
  //   'Saidapet',
  //   'Saidapet Bridge',
  //   'Saidapet Veterinary Hospital Or Raja Hostel',
  //   'Saint Anthony Church (Palavakkam',
  //   'Santhome Church',
  //   'Santhosapuram',
  //   'Saravana Store Chromepet',
  //   'Satyabhama University',
  //   'Sayani Theatre Aynavaram',
  //   'Secretariat',
  //   'Seevaram',
  //   'Sembakkam',
  //   'Semmancheri',
  //   'Senneerkuppam',
  //   'Senneerkuppam Electronic Board House',
  //   'Shanthi Theatre',
  //   'Sholinganallur',
  //   'Shri Nagathaman Temple',
  //   'Siet Gst',
  //   'Simson Or聽Periyar Bridge',
  //   'Sipcot',
  //   'Sirucheri IT Park',
  //   'Sivet',
  //   'Spensor Plaza TVS',
  //   'SrBharathi Nagar',
  //   'St Thomas Mount Head Post Office',
  //   'Stedford Hospital',
  //   'Swami Vivekananda House',
  //   'T S Krishna Nagar',
  //   'T.I Miller',
  //   'TB Hospital',
  //   'TB Hospital Ayanavaram',
  //   'TCS Karapakkam',
  //   'TI school Opp.',
  //   'Tambaram East Bus Stop',
  //   'Tambaram Sanatorium Bus Stand',
  //   'Tambaram West Bus Stand',
  //   'Tansi Nagar',
  //   'Telephone Exchange',
  //   'Telephone Exchange Guindy',
  //   'Thadandar Nagar',
  //   'Tharamani Or IRTC Junction',
  //   'Thinathanthi',
  //   'Thirumangalam',
  //   'Thirumangalam EB Office',
  //   'Thirumangalam Or Sunguvarchattram',
  //   'Thirumazhisai Bus Stand',
  //   'Thirumazhisai Koil',
  //   'Thirumullaivoyal',
  //   'Thirunagar',
  //   'Thiruporur Bus Stand',
  //   'Thiruporur Kovil',
  //   'Thiruporur Or Kannagapattu',
  //   'Thiruvalluvar Nagar RTO',
  //   'Thiruvanmiyur Depot',
  //   'Thiruvanmiyur Or Marudeeswarar Temple',
  //   'Thiyagaraya Nagar Bus Depot',
  //   'Thousand light Or U S Embassy',
  //   'Tidel Park',
  //   'Trade Centre Nandambakkam',
  //   'Trustpuram',
  //   'Tube Products of India',
  //   'UTI Bank',
  //   'Uppukarpettai',
  //   'Uthandi',
  //   'Uthandi Toll Gate / Ragash College',
  //   'V.G.P. Golden Beach',
  //   'Vadapalani',
  //   'Vadapalani Bus Stand',
  //   'Vadapalani Kovil',
  //   'Vaishnavi Nagar',
  //   'Valasaravakkam',
  //   'Vallalar Nagar Bus Depot',
  //   'Valluvar Kottam',
  //   'Vanavil',
  //   'Vaniyanchavadi Padma Adarsh School',
  //   'Varadaraja Puram',
  //   'Vasantham Nagar',
  //   'Vathal Thottam',
  //   'Veerapuram',
  //   'Veerapuram Road Junction',
  //   'Veerapuram Viraliyur Kodi',
  //   'Veeraraghavapuram',
  //   'Vel Tech Junction',
  //   'Velachery',
  //   'Velachery Erikarai',
  //   'Velachery Railway Station',
  //   'Vellacherry Check Post',
  //   'Vellavedu',
  //   'Vetnary Hospital',
  //   'Vetrivel Theatre',
  //   'Vettuvakeni',
  //   'Vidyodaya School Valluvar Kottam',
  //   'Vigneshwara Nagar Porur',
  //   'Vijaya Shanthi Lotus Pond',
  //   'Villivakkam Kalpana',
  //   'Virugambakkam',
  //   'Vivekananda School',
  //   'Viveks And Company',
  //   'War Memorial',
  //   'Womens Polytechnic College',
  //   'Y W C A',
  //   'Yadhava Street'
  // ];

  static final List<String> states = [
    'ganga',
    'himalaya',
    'gymkhana',
    'clt',
    'oat',
    'library',
    'Admin Block',
    'gajendra',
    'hospital',
    'humanity science block(hsb)',
    'icsr',
    'engineering design',
    'ocean engineering',
    'crc',
    'bsb',
    'velachery',
    'main gate',
    'residential',
    'Vana Vani',
    'link road',
    'kv'
  ];

  static List<String> getSuggestions(String query) {
    List<String> matches = [];
    matches.addAll(states);
    matches.retainWhere((s) => s.toLowerCase().contains(query.toLowerCase()));
    return matches;
  }
}
